on: push

jobs:
  opentofu_test:
    name: "Run OpenTofu Test"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: "arn:aws:iam::752995910526:role/lambda-sample-tests"
          role-session-name: "infra-test-session"
          aws-region: "eu-west-3"
      - uses: opentofu/setup-opentofu@v1
      - name: Tofu test
        env: 
          TF_VAR_name: lambda-sample-${{ github.run_id }}
        working-directory: td5/scripts/tofu/live/lambda-sample
        run: |
          tofu init -backend=false -input=false
          tofu test -verbose